---
- name: Maak 10 Proxmox LXC-containers
  hosts: proxmox
  become: yes  # Zorg ervoor dat je het juiste privilege-escalatie mechanisme hebt geconfigureerd

  tasks:
    - name: Maak LXC-container
      proxmox_kvm:
        node: "{{ inventory_hostname }}"
        vmid: "{{ item }}"
        vmtype: lxc
        ostemplate: local:vztmpl/debian-11-turnkey-wordpress_17.1-1_amd64.tar.gz
        storage: local-lvm
        cores: 1
        memory: 1024
        net0: name=eth0,bridge=vmbr0,rate=50
      loop: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

    - name: Wacht even
      pause:
        seconds: 5
