---
- name: Wordpress configuratie
  hosts: all
  become: yes
  vars:
    container_ids:
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
  tasks:
    - name: Containers bouwen
      command: "pct create {{ item }} local:vztmpl/debian-11-turnkey-wordpress_17.1-1_amd64.tar.gz --rootfs local-lvm:30 --cores 1 --memory 1024 --net0 name=eth0,bridge=vmbr0,rate=50"
      loop: "{{ container_ids }}"
      ignore_errors: yes
      register: create_container_results

    - name: C0ntainertjes
      command: "pct set {{ item }} -onboot 1"
      loop: "{{ container_ids }}"
      ignore_errors: yes
      register: setup_container_results
